CREATE TABLE [dbo].[tblTable](
	[iId] [int] NOT NULL,
	[sName] [varchar](50) NOT NULL,
	[sLastName] [varchar](50) NULL,
 CONSTRAINT [PK_tblTable] PRIMARY KEY CLUSTERED
(
	[iId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]